export const ENDPOINTS = {
	auth: {
		login: '/auth/login/',
		refresh: '/auth/refresh/',
		register: '/auth/register/',
		logout: '/auth/logout/',
		me: '/auth/me/',
	},
	employees: {
		list: '/employees/',
		create: '/employees/create/',
		detail: (id) => `/employees/${id}/`,
		update: (id) => `/employees/${id}/update/`,
		delete: (id) => `/employees/${id}/delete/`,
		me: '/employees/me/',
	},
	projects: {
		list: '/projects/',
		create: '/projects/create/',
		detail: (id) => `/projects/${id}/`,
		update: (id) => `/projects/${id}/update/`,
		delete: (id) => `/projects/${id}/delete/`,
		addMember: (id) => `/projects/${id}/add-member/`,
		removeMember: (id) => `/projects/${id}/remove-member/`,
		myProjects: '/projects/my-projects/',
	},
	tasks: {
		list: '/tasks/',
		create: '/tasks/create/',
		detail: (id) => `/tasks/${id}/`,
		update: (id) => `/tasks/${id}/update/`,
		delete: (id) => `/tasks/${id}/delete/`,
		myTasks: '/tasks/my-tasks/',
		comments: (taskId) => `/tasks/${taskId}/comments/`,
		createComment: (taskId) => `/tasks/${taskId}/comments/create/`,
	},
	notifications: {
		list: '/notifications/',
		create: '/notifications/create/',
		detail: (id) => `/notifications/${id}/`,
		delete: (id) => `/notifications/${id}/delete/`,
		markRead: (id) => `/notifications/${id}/mark-read/`,
		markAllRead: '/notifications/mark-all-read/',
		unreadCount: '/notifications/unread-count/',
	},
	activityLogs: {
		list: '/activity-logs/',
		create: '/activity-logs/create/',
		detail: (id) => `/activity-logs/${id}/`,
		delete: (id) => `/activity-logs/${id}/delete/`,
		myLogs: '/activity-logs/my-logs/',
		stats: '/activity-logs/stats/',
	},
	reports: {
		overview: '/reports/overview/',
		tasksByStatus: '/reports/tasks-by-status/',
		employeeWorkload: '/reports/employee-workload/',
		projectProgress: '/reports/project-progress/',
		weeklyCompletions: '/reports/weekly-completions/',
		departmentSummary: '/reports/department-summary/',
		myDashboard: '/dashboard/me/',
	},
}

export default ENDPOINTS
